version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - crypto_exchange_network

  app:
    build: &build
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_started
    environment:
      - CONFIG_PATH=configs/dev.json
    volumes: &volumes
      - ./crypto_exchange:/app/crypto_exchange
    ports:
      - "8080:8080"
    networks:
      - crypto_exchange_network
    command: pdm run python3 -m crypto_exchange

  redis-test:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - crypto_exchange_network

  test:
    build:
      <<: *build
    depends_on:
      redis-test:
        condition: service_started
    environment:
      - CONFIG_PATH=configs/test.json
    volumes:
      *volumes
    networks:
      - crypto_exchange_network
    command: pdm run pytest

  black:
    build:
      <<: *build
    volumes:
      *volumes
    command: pdm run black .

  mypy:
    build:
      <<: *build
    volumes:
      *volumes
    command: pdm run mypy .

  isort:
    build:
      <<: *build
    volumes:
      *volumes
    command: pdm run isort .

networks:
  crypto_exchange_network:
    driver: bridge
